language: python

python:
    - "2.7"
    - "pypy"
    - "pypy3"
    - "3.3"
    - "3.4"

install:
    - python setup.py install

script:
    -  nosetests --with-coverage --cover-package=yahoo_finance

after_success:
    - pip install --quiet coveralls
    - coveralls
